# Generates Core/DefaultTable.cs (the built-in loot table) from the design tables in this folder.
# Usage: awk -f gen_cs.awk high_difficulty.txt beachcombing.tsv added.tsv removed.tsv > ../../Core/DefaultTable.cs
BEGIN {
  FS = "\t"
  # Category ids are saved in player settings (shares): give a new id when a category changes meaning.
  catId["Хлам, дерево и материалы"] = "JunkMaterials";    catEn["JunkMaterials"] = "Junk, wood & materials"
  catId["Природное"] = "Nature";                          catEn["Nature"] = "Nature"
  catId["Рыбалка и стрелы"] = "FishingArrows";            catEn["FishingArrows"] = "Fishing gear & arrows"
  catId["Огонь, сигналы и боеприпасы"] = "FireSignalAmmo"; catEn["FireSignalAmmo"] = "Fire, flares & ammo"
  catId["Еда"] = "Food";                                  catEn["Food"] = "Food"
  catId["Инструменты и снаряжение"] = "Tools";            catEn["Tools"] = "Tools & equipment"
  catId["Медицина"] = "Medicine";                         catEn["Medicine"] = "Medicine"
  catId["Мелкая одежда и обувь"] = "SmallClothingFootwear"; catEn["SmallClothingFootwear"] = "Accessories & footwear"
  catId["Одежда и верхняя одежда"] = "ClothingOuterwear"; catEn["ClothingOuterwear"] = "Clothing & outerwear"
  tier["Частый"] = "Frequent"; tier["Обычный"] = "Common"; tier["Редкий"] = "Rare"
  tier["Очень редкий"] = "VeryRare"; tier["Исключительный"] = "Exceptional"
}
FILENAME ~ /high_difficulty/ { hd[$1] = 1; next }
FILENAME ~ /beachcombing|added/ {
  if (!($1 in share)) { share[$1] = $2; corder[++nc] = $1 }
  origin = (FILENAME ~ /added/) ? "Added" : "Beachcombing"
  item($4, $5, $6, $1, $3, origin); next
}
FILENAME ~ /removed/ {
  gear = $3
  if (gear ~ /^GEAR_BookA/) gear = "GEAR_BookA,GEAR_BookB,GEAR_BookC,GEAR_BookD,GEAR_BookE,GEAR_BookF,GEAR_BookG,GEAR_BookH,GEAR_BookI"
  item($1, $2, gear, $4, $5, "Removed"); next
}
function item(en, ru, gear, cat, t, origin,   dlc, g, n, i, s) {
  dlc = (ru ~ /\(DLC\)/) ? "true" : "false"
  sub(/ \(DLC\)/, "", ru); sub(/ \(шутка\)/, "", ru); sub(/, 3 вида/, "", ru)
  gsub(/"/, "\\\"", en); gsub(/"/, "\\\"", ru)
  n = split(gear, g, ","); s = ""
  for (i = 1; i <= n; i++) s = s (i > 1 ? ", " : "") "\"" g[i] "\""
  lines[++ni] = sprintf("            I(\"%s\", \"%s\", Cat.%s, Tier.%s, Origin.%s, %s, %s, %s),", en, ru, catId[cat], tier[t], origin, dlc, (g[1] in hd) ? "true" : "false", s)
}
END {
  print "// <auto-generated> from docs/data/*.tsv by docs/data/gen_cs.awk. Edit the tables, not this file. </auto-generated>"
  print "using System.Collections.Generic;"
  print ""
  print "namespace FishingFinds"
  print "{"
  print "    internal static class DefaultTable"
  print "    {"
  print "        private static class Cat"
  print "        {"
  for (i = 1; i <= nc; i++) printf "            public const string %s = \"%s\";\n", catId[corder[i]], catId[corder[i]]
  print "        }"
  print ""
  print "        public static List<CategoryData> Categories() => new()"
  print "        {"
  for (i = 1; i <= nc; i++) { c = corder[i]; id = catId[c]; printf "            new CategoryData { Id = Cat.%s, NameEn = \"%s\", NameRu = \"%s\", Share = %d },\n", id, catEn[id], c, share[c] }
  print "        };"
  print ""
  print "        public static List<ItemData> Items() => new()"
  print "        {"
  for (i = 1; i <= ni; i++) print lines[i]
  print "        };"
  print ""
  print "        private static ItemData I(string en, string ru, string category, Tier tier, Origin origin, bool dlc, bool highDifficulty, params string[] gear) =>"
  print "            new() { Id = gear[0], NameEn = en, NameRu = ru, Category = category, Tier = tier, Origin = origin, Dlc = dlc, HighDifficulty = highDifficulty, Gear = gear };"
  print "    }"
  print "}"
}
